export default {
    TITLE_MIN_LEN: 3,
    TITLE_MAX_LEN: 50,
    CONTENT_MIN_LEN: 3,
    CONTENT_MAX_LEN: 5000,
    PORTIONS_MIN: 1,
    PORTIONS_MAX: 1000,
    PREP_TIME_MIN: 1,
    PREP_TIME_MAX: 1000,
    COOK_TIME_MIN: 1,
    COOK_TIME_MAX: 1000,
}